import '../models/coches.dart';

class CochesController {
  static List<Coche> coches = [
    Coche(
      nombre: 'Ford',
      modelo: 'Focus',
      imagen: '../assets/car1.png',
      descripcion: 'Compacto con gran rendimiento y tecnología avanzada.',
      precio: 20000.00,
      ano: 2021,
      color: 'Amarillo',
      transmision: 'Automática',
    ),
    Coche(
      nombre: 'Audi',
      modelo: 'A3',
      imagen: '../assets/car2.png',
      descripcion: 'Elegante, deportivo y eficiente.',
      precio: 25000.00,
      ano: 2022,
      color: 'Azul',
      transmision: 'Manual',
    ),
    Coche(
      nombre: 'BMW',
      modelo: 'Serie 3',
      imagen: '../assets/car3.png',
      descripcion: 'Deportividad y tecnología de punta.',
      precio: 35000.00,
      ano: 2023,
      color: 'Negro',
      transmision: 'Automática',
    ),
    Coche(
      nombre: 'Mercedes',
      modelo: 'Clase A',
      imagen: '../assets/car4.png',
      descripcion: 'Lujo y comodidad en un compacto.',
      precio: 30000.00,
      ano: 2021,
      color: 'Blanco',
      transmision: 'Automática',
    ),
    Coche(
      nombre: 'Renault',
      modelo: 'Megane',
      imagen: '../assets/car5.png',
      descripcion: 'Versatilidad y rendimiento para la ciudad.',
      precio: 18000.00,
      ano: 2020,
      color: 'Gris',
      transmision: 'Manual',
    ),
    Coche(
      nombre: 'Seat',
      modelo: 'Ibiza',
      imagen: '../assets/car3.png',
      descripcion: 'Perfecto para la ciudad, ágil y eficiente.',
      precio: 15000.00,
      ano: 2021,
      color: 'Amarillo',
      transmision: 'Manual',
    ),
    Coche(
      nombre: 'Volkswagen',
      modelo: 'Golf',
      imagen: '../assets/car1.png',
      descripcion: 'El clásico hatchback renovado.',
      precio: 22000.00,
      ano: 2022,
      color: 'Verde',
      transmision: 'Automática',
    ),
    Coche(
      nombre: 'Peugeot',
      modelo: '308',
      imagen: '../assets/car2.png',
      descripcion: 'Estilo y tecnología francesa.',
      precio: 20000.00,
      ano: 2022,
      color: 'Rojo',
      transmision: 'Manual',
    ),
    Coche(
      nombre: 'Opel',
      modelo: 'Astra',
      imagen: '../assets/car4.png',
      descripcion: 'Diseño innovador con gran desempeño.',
      precio: 19000.00,
      ano: 2020,
      color: 'Azul',
      transmision: 'Automática',
    ),
    Coche(
      nombre: 'Citroën',
      modelo: 'C4',
      imagen: '../assets/car5.png',
      descripcion: 'Compacto, cómodo y eficiente.',
      precio: 17000.00,
      ano: 2021,
      color: 'Blanco',
      transmision: 'Manual',
    ),
    Coche(
      nombre: 'Tesla',
      modelo: 'Model 3',
      imagen: '../assets/car1.png',
      descripcion: 'El futuro eléctrico con tecnología de punta.',
      precio: 50000.00,
      ano: 2023,
      color: 'Negro',
      transmision: 'Automática',
    ),
    Coche(
      nombre: 'Chevrolet',
      modelo: 'Cruze',
      imagen: '../assets/car2.png',
      descripcion: 'Sedán compacto con gran estilo.',
      precio: 21000.00,
      ano: 2021,
      color: 'Gris',
      transmision: 'Manual',
    ),
    Coche(
      nombre: 'Toyota',
      modelo: 'Corolla',
      imagen: '../assets/car3.png',
      descripcion: 'Fiabilidad y eficiencia comprobadas.',
      precio: 23000.00,
      ano: 2022,
      color: 'Azul',
      transmision: 'Automática',
    ),
    Coche(
      nombre: 'Hyundai',
      modelo: 'Elantra',
      imagen: '../assets/car4.png',
      descripcion: 'Diseño audaz y tecnología avanzada.',
      precio: 24000.00,
      ano: 2022,
      color: 'Rojo',
      transmision: 'Manual',
    ),
    Coche(
      nombre: 'Kia',
      modelo: 'Rio',
      imagen: '../assets/car5.png',
      descripcion: 'Compacto, cómodo y versátil.',
      precio: 16000.00,
      ano: 2021,
      color: 'Blanco',
      transmision: 'Automática',
    ),
  ];
}
